// XIOM — Documentation Generator
// Copyright (c) 2026 Eleftherios Notas
// Licensed under the MIT or Apache-2.0 license, at your option.

use std::env;
use std::fs;
use std::process;

use xiom_ast::*;
use xiom_lexer::Lexer;
use xiom_parser::Parser;

const VERSION: &str = env!("CARGO_PKG_VERSION");

fn xiom_version() -> &'static str {
    option_env!("XIOM_RELEASE_TAG").unwrap_or("0.52.1")
}

fn main() {
    let args: Vec<String> = env::args().collect();

    if args.iter().any(|a| a == "--help") {
        print_usage();
        return;
    }
    if args.iter().any(|a| a == "--version") {
        eprintln!("xiom-doc v{}", env!("CARGO_PKG_VERSION"));
        process::exit(0);
    }

    if args.len() < 2 {
        print_usage();
        process::exit(1);
    }

    let html_mode = args.iter().any(|a| a == "--html" || a == "--format=html");
    let file = &args[1];
    let source = fs::read_to_string(file).unwrap_or_else(|e| {
        eprintln!("xiom doc: {}: {}", file, e);
        process::exit(1);
    });

    let mut lexer = Lexer::new(&source);
    let tokens = lexer.tokenize();
    let mut parser = Parser::new(tokens);

    match parser.parse_program() {
        Ok(program) => {
            if html_mode {
                generate_docs_html(&program, file);
            } else {
                println!("# XIOM API Documentation");
                println!();
                println!("> Generated by `xiom doc` from `{}`", file);
                println!();
                generate_docs(&program, 0);
            }
        }
        Err(e) => {
            eprintln!("xiom doc: parse error: {:?}", e);
            process::exit(1);
        }
    }
}

fn generate_docs(program: &Program, _depth: usize) {
    print!("{}", generate_docs_str(program));
}

fn generate_docs_str(program: &Program) -> String {
    let mut out = String::new();
    for item in &program.items {
        out.push_str(&doc_item_str(item, 0));
    }
    out
}

fn doc_item_str(item: &TopDecl, depth: usize) -> String {
    let prefix = "#".repeat(depth + 2);
    match item {
        TopDecl::Fn(f) if f.is_pub => {
            let mut out = String::new();
            out.push_str(&format!("{} `fn {}`\n\n", prefix, fn_signature(f)));
            for c in &f.contracts {
                match c {
                    ContractClause::Requires(e, _) => {
                        out.push_str(&format!("- **Precondition:** `{}`\n", expr_to_string(e)));
                    }
                    ContractClause::Ensures(e, _) => {
                        out.push_str(&format!("- **Postcondition:** `{}`\n", expr_to_string(e)));
                    }
                }
            }
            if !f.contracts.is_empty() { out.push('\n'); }
            out
        }
        TopDecl::Type(td) if td.is_pub => {
            let mut out = String::new();
            out.push_str(&format!("{} `type {}`\n\n", prefix, td.name.name));
            out.push_str("| Field | Type |\n");
            out.push_str("|-------|------|\n");
            for field in &td.fields {
                out.push_str(&format!("| `{}` | `{}` |\n", field.name.name, xiom_display::type_to_string(&field.ty)));
            }
            out.push('\n');
            if !td.invariants.is_empty() {
                out.push_str("**Invariants:**\n");
                for inv in &td.invariants {
                    out.push_str(&format!("- `{}`\n", expr_to_string(inv)));
                }
                out.push('\n');
            }
            if !td.derives.is_empty() {
                let derives: Vec<&str> = td.derives.iter().map(|d| match d {
                    DeriveTrait::Eq => "Eq",
                    DeriveTrait::Clone => "Clone",
                    DeriveTrait::Display => "Display",
                    DeriveTrait::Hash => "Hash",
                    DeriveTrait::Ord => "Ord",
                    DeriveTrait::Debug => "Debug",
                }).collect();
                out.push_str(&format!("**Derives:** `{}`\n\n", derives.join(", ")));
            }
            out
        }
        TopDecl::Enum(ed) if ed.is_pub => {
            let mut out = String::new();
            out.push_str(&format!("{} `enum {}`\n\n", prefix, ed.name.name));
            for v in &ed.variants {
                if v.fields.is_empty() {
                    out.push_str(&format!("- `{}`\n", v.name.name));
                } else {
                    let fields: Vec<String> = v.fields.iter()
                        .map(|f| format!("{}: {}", f.name.name, xiom_display::type_to_string(&f.ty)))
                        .collect();
                    out.push_str(&format!("- `{}({})`\n", v.name.name, fields.join(", ")));
                }
            }
            out.push('\n');
            out
        }
        TopDecl::Module(m) => {
            let heading = if depth == 0 { "#".to_string() } else { "#".repeat(depth + 2) };
            let mut out = String::new();
            out.push_str(&format!("{} Module `{}`\n\n", heading, m.name.name));
            out.push_str(&generate_docs_inner_str(&m.items, depth + 1));
            out.push_str("---\n\n");
            out
        }
        _ => String::new(),
    }
}

fn generate_docs_inner_str(items: &[TopDecl], depth: usize) -> String {
    let mut out = String::new();
    for item in items {
        out.push_str(&doc_item_str(item, depth));
    }
    out
}

fn fn_signature(f: &FnDecl) -> String {
    let mut s = String::new();
    s.push_str(&f.name.name);
    if !f.generics.is_empty() {
        s.push('[');
        for (i, g) in f.generics.iter().enumerate() {
            if i > 0 { s.push_str(", "); }
            s.push_str(&g.name.name);
        }
        s.push(']');
    }
    s.push('(');
    for (i, p) in f.params.iter().enumerate() {
        if i > 0 { s.push_str(", "); }
        s.push_str(&format!("{}: {}", p.name.name, xiom_display::type_to_string(&p.ty)));
    }
    s.push(')');
    if let Some(ref ret) = f.return_type {
        s.push_str(&format!(" -> {}", xiom_display::type_to_string(ret)));
    }
    s
}

// Phase 8B: type_to_string/op_to_str/pattern_to_string delegated to xiom-display.
// expr_to_string kept locally (xiom-display doesn't export it yet).

fn op_to_str(op: &BinOp) -> &str { xiom_display::op_to_str(op) }
fn pattern_to_string(pat: &Pattern) -> String { xiom_display::pattern_to_string(pat) }

fn expr_to_string(expr: &Expr) -> String {
    match expr {
        Expr::Ident(id) => id.name.clone(),
        Expr::Int(n, _) => n.to_string(),
        Expr::Float(f, _) => f.to_string(),
        Expr::Bool(b, _) => if *b { "true".to_string() } else { "false".to_string() },
        Expr::Str(s, _) => format!("\"{}\"", s),
        Expr::Char(c, _) => format!("'{}'", c),
        Expr::Binary(left, op, right, _) => {
            format!("{} {} {}", expr_to_string(left), op_to_str(op), expr_to_string(right))
        }
        Expr::Unary(op, inner, _) => {
            use xiom_display::unary_op_to_str;
            format!("{}{}", unary_op_to_str(op), expr_to_string(inner))
        }
        Expr::Call(func, args, _) => {
            let args: Vec<String> = args.iter().map(expr_to_string).collect();
            format!("{}({})", expr_to_string(func), args.join(", "))
        }
        Expr::Field(obj, field, _) => format!("{}.{}", expr_to_string(obj), field.name),
        Expr::Paren(inner, _) => format!("({})", expr_to_string(inner)),
        Expr::Index(obj, index, _) => format!("{}[{}]", expr_to_string(obj), expr_to_string(index)),
        Expr::Try(inner, _) => format!("{}?", expr_to_string(inner)),
        Expr::Some(inner, _) => format!("Some({})", expr_to_string(inner)),
        Expr::None(_) => "None".to_string(),
        Expr::Ok(inner, _) => format!("Ok({})", expr_to_string(inner)),
        Expr::Err(inner, _) => format!("Err({})", expr_to_string(inner)),
        Expr::AtPre(inner, _) => format!("{}@pre", expr_to_string(inner)),
        Expr::Ref(inner, _) => format!("&{}", expr_to_string(inner)),
        Expr::MutRef(inner, _) => format!("&mut {}", expr_to_string(inner)),
        Expr::Imply(left, right, _) => format!("{} => {}", expr_to_string(left), expr_to_string(right)),
        Expr::Is(expr, pat, _) => format!("{} is {}", expr_to_string(expr), pattern_to_string(pat)),
        _ => "?".to_string(),
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use xiom_lexer::Lexer;
    use xiom_parser::Parser;

    fn parse_and_generate(source: &str) -> String {
        let mut lexer = Lexer::new(source);
        let tokens = lexer.tokenize();
        let mut parser = Parser::new(tokens);
        let program = parser.parse_program().expect("parse failed");
        generate_docs_str(&program)
    }

    #[test]
    fn test_doc_fn() {
        let source = "pub fn add(a: Int, b: Int) -> Int { a + b }";
        let result = parse_and_generate(source);
        assert!(result.contains("fn add"));
        assert!(result.contains("Int"));
    }

    #[test]
    fn test_doc_struct() {
        let source = "pub type Point = { x: Float64; y: Float64; }";
        let result = parse_and_generate(source);
        assert!(result.contains("`type Point`"));
        assert!(result.contains("| `x` | `Float64` |"));
        assert!(result.contains("| `y` | `Float64` |"));
    }

    #[test]
    fn test_doc_pub_only() {
        let source = "pub fn visible() -> Int { 0 }\nfn hidden() -> Int { 0 }";
        let result = parse_and_generate(source);
        assert!(result.contains("visible"));
        assert!(!result.contains("hidden"));
    }

    #[test]
    fn test_doc_empty() {
        let source = "";
        let result = parse_and_generate(source);
        assert!(result.is_empty());
    }
}

/// 8B/M8: Generate HTML documentation output.
fn generate_docs_html(program: &Program, source_file: &str) {
    println!("<!DOCTYPE html>");
    println!("<html><head><meta charset=\"utf-8\"><title>XIOM API — {source_file}</title>");
    println!("<style>body{{font-family:system-ui,sans-serif;max-width:900px;margin:0 auto;padding:20px;}}");
    println!("h1{{color:#333}}h2{{border-bottom:2px solid #eee;padding-bottom:4px}}");
    println!(".fn{{background:#f5f5f5;padding:12px;border-radius:4px;margin:8px 0}}");
    println!(".fn-name{{font-weight:bold;font-family:monospace;font-size:1.1em}}");
    println!(".params{{color:#666;font-family:monospace}}");
    println!(".contract{{font-size:0.9em;color:#856404;background:#fff3cd;padding:4px 8px;margin:4px 0;border-radius:3px}}");
    println!("table{{border-collapse:collapse}}th,td{{padding:4px 12px;text-align:left}}th{{background:#eee}}</style>");
    println!("</head><body>");
    println!("<h1>XIOM API Documentation</h1>");
    println!("<p>Generated from <code>{source_file}</code></p>");
    println!("<hr>");
    generate_docs_html_items(&program.items, 2);
    println!("</body></html>");
}

fn generate_docs_html_items(items: &[TopDecl], depth: usize) {
    for item in items {
        match item {
            TopDecl::Fn(f) if f.is_pub => {
                println!("<div class=\"fn\">");
                println!("<div class=\"fn-name\">{}</div>", fn_signature(f));
                for c in &f.contracts {
                    match c {
                        ContractClause::Requires(e, _) => {
                            println!("<div class=\"contract\">Pre: {}</div>", expr_to_string(e));
                        }
                        ContractClause::Ensures(e, _) => {
                            println!("<div class=\"contract\">Post: {}</div>", expr_to_string(e));
                        }
                    }
                }
                println!("</div>");
            }
            TopDecl::Type(td) if td.is_pub => {
                println!("<h{depth}>type {}</h{depth}>", td.name.name);
                println!("<table><tr><th>Field</th><th>Type</th></tr>");
                for field in &td.fields {
                    println!("<tr><td><code>{}</code></td><td><code>{}</code></td></tr>",
                        field.name.name, xiom_display::type_to_string(&field.ty));
                }
                println!("</table>");
            }
            TopDecl::Enum(ed) if ed.is_pub => {
                println!("<h{depth}>enum {}</h{depth}>", ed.name.name);
                println!("<ul>");
                for v in &ed.variants {
                    if v.fields.is_empty() {
                        println!("<li><code>{}</code></li>", v.name.name);
                    } else {
                        let fields: Vec<String> = v.fields.iter()
                            .map(|f| format!("{}: {}", f.name.name, xiom_display::type_to_string(&f.ty)))
                            .collect();
                        println!("<li><code>{}({})</code></li>", v.name.name, fields.join(", "));
                    }
                }
                println!("</ul>");
            }
            TopDecl::Module(m) => {
                println!("<h{depth}>{}</h{depth}>", m.name.name);
                generate_docs_html_items(&m.items, depth + 1);
            }
            _ => {}
        }
    }
}

fn print_usage() {
    eprintln!("XIOM Doc v{} — Documentation Generator", VERSION);
    eprintln!();
    eprintln!("USAGE:");
    eprintln!("  xiom doc <file.xi> [--html]");
    eprintln!();
    eprintln!("OPTIONS:");
    eprintln!("  --help        Show this help message");
    eprintln!("  --version     Show version information");
    eprintln!("  --html        Output HTML instead of Markdown");
    eprintln!();
    eprintln!("EXAMPLES:");
    eprintln!("  xiom doc examples/phase1_contracts.xi");
    eprintln!("  xiom doc lib.xi --html > api.html");
}
