// XIOM — Documentation Generator
// Copyright (c) 2026 Eleftherios Notas
// Licensed under the MIT or Apache-2.0 license, at your option.

use std::env;
use std::fs;
use std::process;

use xiom_ast::*;
use xiom_lexer::Lexer;
use xiom_parser::Parser;

const VERSION: &str = env!("CARGO_PKG_VERSION");

fn xiom_version() -> &'static str {
    option_env!("XIOM_RELEASE_VERSION").unwrap_or("0.49.7")
}

fn main() {
    let args: Vec<String> = env::args().collect();

    if args.iter().any(|a| a == "--help") {
        print_usage();
        return;
    }
    if args.iter().any(|a| a == "--version") {
        eprintln!("xiom-doc v{} (XIOM v{})", VERSION, xiom_version());
        return;
    }

    if args.len() < 2 {
        print_usage();
        process::exit(1);
    }

    let file = &args[1];
    let source = fs::read_to_string(file).unwrap_or_else(|e| {
        eprintln!("xiom doc: {}: {}", file, e);
        process::exit(1);
    });

    let mut lexer = Lexer::new(&source);
    let tokens = lexer.tokenize();
    let mut parser = Parser::new(tokens);

    match parser.parse_program() {
        Ok(program) => {
            println!("# XIOM API Documentation");
            println!();
            println!("> Generated by `xiom doc` from `{}`", file);
            println!();
            generate_docs(&program, 0);
        }
        Err(e) => {
            eprintln!("xiom doc: parse error: {:?}", e);
            process::exit(1);
        }
    }
}

fn generate_docs(program: &Program, _depth: usize) {
    print!("{}", generate_docs_str(program));
}

fn generate_docs_str(program: &Program) -> String {
    let mut out = String::new();
    for item in &program.items {
        out.push_str(&doc_item_str(item, 0));
    }
    out
}

fn doc_item_str(item: &TopDecl, depth: usize) -> String {
    let prefix = "#".repeat(depth + 2);
    match item {
        TopDecl::Fn(f) if f.is_pub => {
            let mut out = String::new();
            out.push_str(&format!("{} `fn {}`\n\n", prefix, fn_signature(f)));
            for c in &f.contracts {
                match c {
                    ContractClause::Requires(e, _) => {
                        out.push_str(&format!("- **Precondition:** `{}`\n", expr_to_string(e)));
                    }
                    ContractClause::Ensures(e, _) => {
                        out.push_str(&format!("- **Postcondition:** `{}`\n", expr_to_string(e)));
                    }
                }
            }
            if !f.contracts.is_empty() { out.push('\n'); }
            out
        }
        TopDecl::Type(td) if td.is_pub => {
            let mut out = String::new();
            out.push_str(&format!("{} `type {}`\n\n", prefix, td.name.name));
            out.push_str("| Field | Type |\n");
            out.push_str("|-------|------|\n");
            for field in &td.fields {
                out.push_str(&format!("| `{}` | `{}` |\n", field.name.name, xiom_display::type_to_string(&field.ty)));
            }
            out.push('\n');
            if !td.invariants.is_empty() {
                out.push_str("**Invariants:**\n");
                for inv in &td.invariants {
                    out.push_str(&format!("- `{}`\n", expr_to_string(inv)));
                }
                out.push('\n');
            }
            if !td.derives.is_empty() {
                let derives: Vec<&str> = td.derives.iter().map(|d| match d {
                    DeriveTrait::Eq => "Eq",
                    DeriveTrait::Clone => "Clone",
                    DeriveTrait::Display => "Display",
                    DeriveTrait::Hash => "Hash",
                    DeriveTrait::Ord => "Ord",
                }).collect();
                out.push_str(&format!("**Derives:** `{}`\n\n", derives.join(", ")));
            }
            out
        }
        TopDecl::Enum(ed) if ed.is_pub => {
            let mut out = String::new();
            out.push_str(&format!("{} `enum {}`\n\n", prefix, ed.name.name));
            for v in &ed.variants {
                if v.fields.is_empty() {
                    out.push_str(&format!("- `{}`\n", v.name.name));
                } else {
                    let fields: Vec<String> = v.fields.iter()
                        .map(|f| format!("{}: {}", f.name.name, xiom_display::type_to_string(&f.ty)))
                        .collect();
                    out.push_str(&format!("- `{}({})`\n", v.name.name, fields.join(", ")));
                }
            }
            out.push('\n');
            out
        }
        TopDecl::Module(m) => {
            let heading = if depth == 0 { "#".to_string() } else { "#".repeat(depth + 2) };
            let mut out = String::new();
            out.push_str(&format!("{} Module `{}`\n\n", heading, m.name.name));
            out.push_str(&generate_docs_inner_str(&m.items, depth + 1));
            out.push_str("---\n\n");
            out
        }
        _ => String::new(),
    }
}

fn generate_docs_inner_str(items: &[TopDecl], depth: usize) -> String {
    let mut out = String::new();
    for item in items {
        out.push_str(&doc_item_str(item, depth));
    }
    out
}

fn fn_signature(f: &FnDecl) -> String {
    let mut s = String::new();
    s.push_str(&f.name.name);
    if !f.generics.is_empty() {
        s.push('[');
        for (i, g) in f.generics.iter().enumerate() {
            if i > 0 { s.push_str(", "); }
            s.push_str(&g.name.name);
        }
        s.push(']');
    }
    s.push('(');
    for (i, p) in f.params.iter().enumerate() {
        if i > 0 { s.push_str(", "); }
        s.push_str(&format!("{}: {}", p.name.name, xiom_display::type_to_string(&p.ty)));
    }
    s.push(')');
    if let Some(ref ret) = f.return_type {
        s.push_str(&format!(" -> {}", xiom_display::type_to_string(ret)));
    }
    s
}

// Phase 8B: type_to_string/op_to_str/pattern_to_string delegated to xiom-display.
// expr_to_string kept locally (xiom-display doesn't export it yet).

fn op_to_str(op: &BinOp) -> &str { xiom_display::op_to_str(op) }
fn pattern_to_string(pat: &Pattern) -> String { xiom_display::pattern_to_string(pat) }

fn expr_to_string(expr: &Expr) -> String {
    match expr {
        Expr::Ident(id) => id.name.clone(),
        Expr::Int(n, _) => n.to_string(),
        Expr::Float(f, _) => f.to_string(),
        Expr::Bool(b, _) => if *b { "true".to_string() } else { "false".to_string() },
        Expr::Str(s, _) => format!("\"{}\"", s),
        Expr::Char(c, _) => format!("'{}'", c),
        Expr::Binary(left, op, right, _) => {
            format!("{} {} {}", expr_to_string(left), op_to_str(op), expr_to_string(right))
        }
        Expr::Unary(op, inner, _) => {
            use xiom_display::unary_op_to_str;
            format!("{}{}", unary_op_to_str(op), expr_to_string(inner))
        }
        Expr::Call(func, args, _) => {
            let args: Vec<String> = args.iter().map(expr_to_string).collect();
            format!("{}({})", expr_to_string(func), args.join(", "))
        }
        Expr::Field(obj, field, _) => format!("{}.{}", expr_to_string(obj), field.name),
        Expr::Paren(inner, _) => format!("({})", expr_to_string(inner)),
        Expr::Index(obj, index, _) => format!("{}[{}]", expr_to_string(obj), expr_to_string(index)),
        Expr::Try(inner, _) => format!("{}?", expr_to_string(inner)),
        Expr::Some(inner, _) => format!("Some({})", expr_to_string(inner)),
        Expr::None(_) => "None".to_string(),
        Expr::Ok(inner, _) => format!("Ok({})", expr_to_string(inner)),
        Expr::Err(inner, _) => format!("Err({})", expr_to_string(inner)),
        Expr::AtPre(inner, _) => format!("{}@pre", expr_to_string(inner)),
        Expr::Ref(inner, _) => format!("&{}", expr_to_string(inner)),
        Expr::MutRef(inner, _) => format!("&mut {}", expr_to_string(inner)),
        Expr::Imply(left, right, _) => format!("{} => {}", expr_to_string(left), expr_to_string(right)),
        Expr::Is(expr, pat, _) => format!("{} is {}", expr_to_string(expr), pattern_to_string(pat)),
        _ => "?".to_string(),
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use xiom_lexer::Lexer;
    use xiom_parser::Parser;

    fn parse_and_generate(source: &str) -> String {
        let mut lexer = Lexer::new(source);
        let tokens = lexer.tokenize();
        let mut parser = Parser::new(tokens);
        let program = parser.parse_program().expect("parse failed");
        generate_docs_str(&program)
    }

    #[test]
    fn test_doc_fn() {
        let source = "pub fn add(a: Int, b: Int) -> Int { a + b }";
        let result = parse_and_generate(source);
        assert!(result.contains("fn add"));
        assert!(result.contains("Int"));
    }

    #[test]
    fn test_doc_struct() {
        let source = "pub type Point = { x: Float64; y: Float64; }";
        let result = parse_and_generate(source);
        assert!(result.contains("`type Point`"));
        assert!(result.contains("| `x` | `Float64` |"));
        assert!(result.contains("| `y` | `Float64` |"));
    }

    #[test]
    fn test_doc_pub_only() {
        let source = "pub fn visible() -> Int { 0 }\nfn hidden() -> Int { 0 }";
        let result = parse_and_generate(source);
        assert!(result.contains("visible"));
        assert!(!result.contains("hidden"));
    }

    #[test]
    fn test_doc_empty() {
        let source = "";
        let result = parse_and_generate(source);
        assert!(result.is_empty());
    }
}

fn print_usage() {
    eprintln!("XIOM Doc v{} — Documentation Generator", VERSION);
    eprintln!();
    eprintln!("USAGE:");
    eprintln!("  xiom doc <file.xi>");
    eprintln!();
    eprintln!("OPTIONS:");
    eprintln!("  --help        Show this help message");
    eprintln!("  --version     Show version information");
    eprintln!();
    eprintln!("EXAMPLES:");
    eprintln!("  xiom doc examples/phase1_contracts.xi");
}
