[package]
license.workspace = true
publish = false
name = "xiom-parser"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
xiom-lexer = { path = "../xiom-lexer" }
xiom-ast = { path = "../xiom-ast" }

[dev-dependencies]
insta = { version = "1", features = ["yaml"] }
