[package]
name = "xiom"
version = "0.53.0"
edition = "2024"

[lib]
name = "xiom"
path = "src/lib.rs"

[[bin]]
name = "xiom"
path = "src/main.rs"

[target.'cfg(windows)'.build-dependencies]
winres = "0.1"

[dependencies]
xiom-lexer = { path = "../xiom-lexer" }
xiom-parser = { path = "../xiom-parser" }
xiom-ast = { path = "../xiom-ast" }
xiom-check = { path = "../xiom-check" }
xiom-codegen = { path = "../xiom-codegen" }
xiom-verify = { path = "../xiom-verify" }
xiom-graph = { path = "../xiom-graph" }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
sha2 = "0.10"
rayon = "1"
ureq = { version = "2", features = ["json"] }
dirs = "5"
libloading = "0.8"

[features]
default = []
nasm = []  # Enable NASM assembly of .asm files for hardware acceleration
