[workspace]
resolver = "2"
members = [
    "crates/axiom-lexer",
    "crates/axiom-ast",
    "crates/axiom-parser",
    "crates/axiom-check",
    "crates/axiom-codegen",
    "crates/axiomc",
    "crates/axiom-fmt",
    "crates/axiom-doc",
    "crates/axiom-lsp",
    "crates/axiom-pkg",
    "crates/axiom-ffigen",
]
