[workspace]
resolver = "2"
members = [
    "crates/xiom-lexer",
    "crates/xiom-ast",
    "crates/xiom-parser",
    "crates/xiom-check",
    "crates/xiom-codegen",
    "crates/xiomc",
    "crates/xiom-fmt",
    "crates/xiom-doc",
    "crates/xiom-lsp",
    "crates/xiom-pkg",
    "crates/xiom-ffigen",
    "crates/xiom-verify",
]
