[package]
name = "xiom-codegen"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
xiom-ast = { path = "../xiom-ast" }
xiom-ctfe = { path = "../xiom-ctfe" }
target-lexicon = "0.12"
rayon = "1"

[dev-dependencies]
xiom-lexer = { path = "../xiom-lexer" }
xiom-parser = { path = "../xiom-parser" }
xiom-check = { path = "../xiom-check" }
xiom-graph = { path = "../xiom-graph" }
xiom = { path = "../xiom" }
toml = "0.8"
