[package]
name = "xiom-codegen"
version = "0.1.0"
edition = "2024"

[dependencies]
xiom-ast = { path = "../xiom-ast" }
cranelift = "0.116"
cranelift-module = "0.116"
cranelift-jit = "0.116"
cranelift-native = "0.116"
target-lexicon = "0.12"

[dev-dependencies]
xiom-lexer = { path = "../xiom-lexer" }
xiom-parser = { path = "../xiom-parser" }
xiom-check = { path = "../xiom-check" }
xiom-graph = { path = "../xiom-graph" }
xiom = { path = "../xiom" }
toml = "0.8"
