// AXIOM — Documentation Generator
// Copyright (c) 2026 Eleftherios Notas
// Licensed under the MIT or Apache-2.0 license, at your option.

use std::env;
use std::fs;
use std::process;

use axiom_ast::*;
use axiom_lexer::Lexer;
use axiom_parser::Parser;

fn main() {
    let args: Vec<String> = env::args().collect();
    if args.len() < 2 {
        eprintln!("axiom doc: missing file operand");
        eprintln!("Usage: axiom doc <file.ax>");
        process::exit(1);
    }

    let file = &args[1];
    let source = fs::read_to_string(file).unwrap_or_else(|e| {
        eprintln!("axiom doc: {}: {}", file, e);
        process::exit(1);
    });

    let mut lexer = Lexer::new(&source);
    let tokens = lexer.tokenize();
    let mut parser = Parser::new(tokens);

    match parser.parse_program() {
        Ok(program) => {
            println!("# AXIOM API Documentation");
            println!();
            println!("> Generated by `axiom doc` from `{}`", file);
            println!();
            generate_docs(&program, 0);
        }
        Err(e) => {
            eprintln!("axiom doc: parse error: {:?}", e);
            process::exit(1);
        }
    }
}

fn generate_docs(program: &Program, depth: usize) {
    for item in &program.items {
        doc_item(item, depth);
    }
}

fn doc_item(item: &TopDecl, depth: usize) {
    let prefix = "#".repeat(depth + 2);
    match item {
        TopDecl::Fn(f) if f.is_pub => {
            println!("{} `fn {}`", prefix, fn_signature(f));
            println!();
            for c in &f.contracts {
                match c {
                    ContractClause::Requires(e, _) => {
                        println!("- **Precondition:** `{}`", expr_to_string(e));
                    }
                    ContractClause::Ensures(e, _) => {
                        println!("- **Postcondition:** `{}`", expr_to_string(e));
                    }
                }
            }
            if !f.contracts.is_empty() { println!(); }
        }
        TopDecl::Type(td) if td.is_pub => {
            println!("{} `type {}`", prefix, td.name.name);
            println!();
            println!("| Field | Type |");
            println!("|-------|------|");
            for field in &td.fields {
                println!("| `{}` | `{}` |", field.name.name, type_to_string(&field.ty));
            }
            println!();
            if !td.invariants.is_empty() {
                println!("**Invariants:**");
                for inv in &td.invariants {
                    println!("- `{}`", expr_to_string(inv));
                }
                println!();
            }
            if !td.derives.is_empty() {
                let derives: Vec<&str> = td.derives.iter().map(|d| match d {
                    DeriveTrait::Eq => "Eq",
                    DeriveTrait::Clone => "Clone",
                    DeriveTrait::Display => "Display",
                    DeriveTrait::Hash => "Hash",
                    DeriveTrait::Ord => "Ord",
                }).collect();
                println!("**Derives:** `{}`", derives.join(", "));
                println!();
            }
        }
        TopDecl::Enum(ed) if ed.is_pub => {
            println!("{} `enum {}`", prefix, ed.name.name);
            println!();
            for v in &ed.variants {
                if v.fields.is_empty() {
                    println!("- `{}`", v.name.name);
                } else {
                    let fields: Vec<String> = v.fields.iter()
                        .map(|f| format!("{}: {}", f.name.name, type_to_string(&f.ty)))
                        .collect();
                    println!("- `{}({})`", v.name.name, fields.join(", "));
                }
            }
            println!();
        }
        TopDecl::Module(m) => {
            let heading = if depth == 0 { "#".to_string() } else { "#".repeat(depth + 2) };
            println!("{} Module `{}`", heading, m.name.name);
            println!();
            generate_docs_inner(&m.items, depth + 1);
            println!("---");
            println!();
        }
        _ => {}
    }
}

fn generate_docs_inner(items: &[TopDecl], depth: usize) {
    for item in items {
        doc_item(item, depth);
    }
}

fn fn_signature(f: &FnDecl) -> String {
    let mut s = String::new();
    s.push_str(&f.name.name);
    if !f.generics.is_empty() {
        s.push('[');
        for (i, g) in f.generics.iter().enumerate() {
            if i > 0 { s.push_str(", "); }
            s.push_str(&g.name.name);
        }
        s.push(']');
    }
    s.push('(');
    for (i, p) in f.params.iter().enumerate() {
        if i > 0 { s.push_str(", "); }
        s.push_str(&format!("{}: {}", p.name.name, type_to_string(&p.ty)));
    }
    s.push(')');
    if let Some(ref ret) = f.return_type {
        s.push_str(&format!(" -> {}", type_to_string(ret)));
    }
    s
}

fn type_to_string(ty: &Type) -> String {
    match ty {
        Type::Named(name, _) => name.name.clone(),
        Type::Ref(inner) => format!("&{}", type_to_string(inner)),
        Type::MutRef(inner) => format!("&mut {}", type_to_string(inner)),
        Type::Option(inner) => format!("Option[{}]", type_to_string(inner)),
        Type::Result(ok, err) => format!("Result[{}, {}]", type_to_string(ok), type_to_string(err)),
        Type::Vec(inner) => format!("Vec[{}]", type_to_string(inner)),
        Type::Slice(inner) => format!("Slice[{}]", type_to_string(inner)),
        Type::Map(k, v) => format!("Map[{}, {}]", type_to_string(k), type_to_string(v)),
        Type::Set(inner) => format!("Set[{}]", type_to_string(inner)),
        Type::Tuple(items) => {
            let inner: Vec<String> = items.iter().map(type_to_string).collect();
            format!("({})", inner.join(", "))
        }
        Type::Ptr(inner) => format!("*{}", type_to_string(inner)),
        Type::Array(size, elem) => format!("[{}]{}", expr_to_string(size), type_to_string(elem)),
    }
}

fn expr_to_string(expr: &Expr) -> String {
    match expr {
        Expr::Ident(id) => id.name.clone(),
        Expr::Int(n, _) => n.to_string(),
        Expr::Float(f, _) => f.to_string(),
        Expr::Bool(b, _) => if *b { "true".to_string() } else { "false".to_string() },
        Expr::Str(s, _) => format!("\"{}\"", s),
        Expr::Char(c, _) => format!("'{}'", c),
        Expr::Binary(left, op, right, _) => {
            format!("{} {} {}", expr_to_string(left), op_to_str(op), expr_to_string(right))
        }
        Expr::Unary(op, inner, _) => {
            format!("{}{}", match op {
                UnaryOp::Not => "!",
                UnaryOp::Neg => "-",
                UnaryOp::Ref => "&",
                UnaryOp::MutRef => "&mut ",
            }, expr_to_string(inner))
        }
        Expr::Call(func, args, _) => {
            let args: Vec<String> = args.iter().map(expr_to_string).collect();
            format!("{}({})", expr_to_string(func), args.join(", "))
        }
        Expr::Field(obj, field, _) => format!("{}.{}", expr_to_string(obj), field.name),
        Expr::Paren(inner, _) => format!("({})", expr_to_string(inner)),
        Expr::Index(obj, index, _) => format!("{}[{}]", expr_to_string(obj), expr_to_string(index)),
        Expr::Try(inner, _) => format!("{}?", expr_to_string(inner)),
        Expr::Some(inner, _) => format!("Some({})", expr_to_string(inner)),
        Expr::None(_) => "None".to_string(),
        Expr::Ok(inner, _) => format!("Ok({})", expr_to_string(inner)),
        Expr::Err(inner, _) => format!("Err({})", expr_to_string(inner)),
        Expr::AtPre(inner, _) => format!("{}@pre", expr_to_string(inner)),
        Expr::Ref(inner, _) => format!("&{}", expr_to_string(inner)),
        Expr::MutRef(inner, _) => format!("&mut {}", expr_to_string(inner)),
        Expr::Imply(left, right, _) => format!("{} => {}", expr_to_string(left), expr_to_string(right)),
        Expr::Is(expr, pat, _) => format!("{} is {}", expr_to_string(expr), pattern_to_string(pat)),
        _ => "?".to_string(),
    }
}

fn pattern_to_string(pat: &Pattern) -> String {
    match pat {
        Pattern::Wildcard(_) => "_".to_string(),
        Pattern::Ident(id) => id.name.clone(),
        Pattern::Variant(name, fields, _) => {
            let f: Vec<String> = fields.iter().map(|id| id.name.clone()).collect();
            format!("{}({})", name.name, f.join(", "))
        }
        Pattern::Lit(lit) => match lit {
            Literal::Int(n, _) => n.to_string(),
            Literal::Float(f, _) => f.to_string(),
            Literal::Str(s, _) => format!("\"{}\"", s),
            Literal::Char(c, _) => format!("'{}'", c),
            Literal::Bool(b, _) => if *b { "true" } else { "false" }.to_string(),
        },
        Pattern::Some(inner, _) => format!("Some({})", pattern_to_string(inner)),
        Pattern::None(_) => "None".to_string(),
        Pattern::Ok(inner, _) => format!("Ok({})", pattern_to_string(inner)),
        Pattern::Err(inner, _) => format!("Err({})", pattern_to_string(inner)),
    }
}

fn op_to_str(op: &BinOp) -> &str {
    match op {
        BinOp::Add => "+", BinOp::Sub => "-", BinOp::Mul => "*", BinOp::Div => "/", BinOp::Rem => "%",
        BinOp::Eq => "==", BinOp::Neq => "!=", BinOp::Lt => "<", BinOp::Gt => ">",
        BinOp::Le => "<=", BinOp::Ge => ">=", BinOp::And => "&&", BinOp::Or => "||",
        BinOp::Assign => "=",
    }
}
