// XIOM -- Selfhost codegen (Phase 0 skeleton)
// Copyright (c) 2026 Eleftherios Notas and The XIOM Authors
// SPDX-License-Identifier: MIT OR Apache-2.0
//
// Phases 4-6 port the Rust emitter to this module. Phase 0 emits a
// well-formed stub module so the T1 harness can prove the driver + stage
// wiring end-to-end; no output here is expected to survive past Phase 4.

module selfhost_codegen

use selfhost_runtime_ffi;

/// Mirrors the Rust compiler's version in the `--emit-ir` header. Keep in
/// step at release time (the Rust side reads CARGO_PKG_VERSION).
const SELFHOST_VERSION: Str = "0.62.2";

/// Phase 0 stub: emit a well-formed IR module (header + `define`).
pub fn emit_program(src: Str) -> Int {
  var out = selfhost_runtime_ffi.rt_ir_open();
  out.raw("; XIOM v" + SELFHOST_VERSION + " LLVM IR");
  out.raw("; Auto-generated by xiom");
  out.raw("; selfhost Phase 0 skeleton -- codegen port pending");
  out.raw("");
  out.raw("define i64 @main() {");
  out.raw("entry0:");
  out.raw("  ret i64 0");
  out.raw("}");
  return out.emit();
}
