[package]
name = "axiomc"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "axiomc"
path = "src/main.rs"

[build-dependencies]
winres = "0.1"

[dependencies]
axiom-lexer = { path = "../axiom-lexer" }
axiom-parser = { path = "../axiom-parser" }
axiom-ast = { path = "../axiom-ast" }
axiom-check = { path = "../axiom-check" }
axiom-codegen = { path = "../axiom-codegen" }
axiom-verify = { path = "../axiom-verify" }
