//! AXIOM Codegen — Phase 0: AST → LLVM IR text.
//! Emits human-readable LLVM IR that can be compiled with `llc`.
//! No external dependencies — pure string emission.
//! Handles: functions, arithmetic, control flow (if/else/while/match),
//! let/var bindings, structs, function calls.

use axiom_ast::*;
use std::collections::HashMap;

// ============================================================================
// LLVM IR Emitter
// ============================================================================

pub struct IrEmitter {
    output: String,
    /// Counter for unique temporary names
    tmp_counter: u32,
    /// Counter for unique block labels
    block_counter: u32,
    /// Counter for unique string constants
    str_counter: u32,
    /// Local variables: name → IR register name
    locals: Vec<HashMap<String, String>>,
    /// Known function signatures: name → (param_count, has_return)
    functions: HashMap<String, (usize, bool)>,
    /// Known type structures: name → field names
    types: HashMap<String, Vec<String>>,
    /// Current function name (for labels)
    current_fn: Option<String>,
    /// Return type of current function (empty = void)
    current_return_type: String,
    /// String constants to emit at the top
    strings: Vec<String>,
}

impl IrEmitter {
    pub fn new() -> Self {
        Self {
            output: String::new(),
            tmp_counter: 0,
            block_counter: 0,
            str_counter: 0,
            locals: vec![HashMap::new()],
            functions: HashMap::new(),
            types: HashMap::new(),
            current_fn: None,
            current_return_type: String::new(),
            strings: Vec::new(),
        }
    }

    fn fresh_tmp(&mut self) -> String {
        let n = self.tmp_counter;
        self.tmp_counter += 1;
        format!("%tmp{n}")
    }

    fn fresh_block(&mut self, label: &str) -> String {
        let n = self.block_counter;
        self.block_counter += 1;
        format!("{label}{n}")
    }

    fn push_scope(&mut self) {
        self.locals.push(HashMap::new());
    }

    fn pop_scope(&mut self) {
        self.locals.pop();
    }

    fn add_local(&mut self, name: &str, reg: String) {
        if let Some(scope) = self.locals.last_mut() {
            scope.insert(name.to_string(), reg);
        }
    }

    fn lookup_local(&self, name: &str) -> Option<&String> {
        for scope in self.locals.iter().rev() {
            if let Some(reg) = scope.get(name) {
                return Some(reg);
            }
        }
        None
    }

    fn emit(&mut self, s: &str) {
        self.output.push_str(s);
    }

    fn emitln(&mut self, s: &str) {
        self.output.push_str(s);
        self.output.push('\n');
    }

    fn axiom_to_llvm_type(axiom_ty: &str) -> &'static str {
        match axiom_ty {
            "Bool" | "Int8" | "UInt8" | "Char" => "i8",
            "Int16" | "UInt16" => "i16",
            "Int32" | "UInt32" => "i32",
            "Int" | "Int64" | "UInt" | "UInt64" => "i64",
            "Float32" => "float",
            "Float64" => "double",
            "Str" => "i8*",
            "()" => "void",
            _ => "i64", // Default: treat unknown types as i64
        }
    }

    fn type_from_ast(ty: &Type) -> String {
        match ty {
            Type::Named(ident, _) => ident.name.clone(),
            Type::Ref(inner) => Self::type_from_ast(inner),
            Type::MutRef(inner) => Self::type_from_ast(inner),
            _ => "Int".to_string(),
        }
    }

    // ========================================================================
    // Program compilation
    // ========================================================================

    pub fn compile_program(&mut self, program: &Program) -> Result<String, String> {
        // Register type structures
        for item in &program.items {
            self.register_type_layout(item);
        }

        // Register function signatures
        for item in &program.items {
            self.register_functions(item);
        }

        // Emit module header
        self.emitln("; AXIOM Phase 0 — LLVM IR");
        self.emitln("; Auto-generated by axiomc\n");

        // Emit string constants
        for s in &self.strings.clone() {
            self.emitln(&s);
        }
        if !self.strings.is_empty() {
            self.emitln("");
        }

        // Emit struct type definitions
        for (name, fields) in &self.types.clone() {
            let field_types: Vec<&str> = fields.iter()
                .map(|_| "i64") // All fields are i64 in Phase 0
                .collect();
            self.emitln(&format!("%struct.{name} = type {{ {} }}", field_types.join(", ")));
        }
        if !self.types.is_empty() {
            self.emitln("");
        }

        // Declare external C functions
        self.emitln("declare i32 @printf(i8*, ...)");
        self.emitln("declare i32 @puts(i8*)");
        self.emitln("");

        // Declare all user functions
        for item in &program.items {
            self.declare_functions_ir(item)?;
        }

        // Define all function bodies
        for item in &program.items {
            self.compile_top_decl(item)?;
        }

        Ok(self.output.clone())
    }

    fn register_type_layout(&mut self, item: &TopDecl) {
        if let TopDecl::Type(td) = item {
            let fields: Vec<String> = td.fields.iter()
                .map(|f| f.name.name.clone())
                .collect();
            self.types.insert(td.name.name.clone(), fields);
        }
        if let TopDecl::Module(md) = item {
            for sub in &md.items {
                self.register_type_layout(sub);
            }
        }
    }

    fn register_functions(&mut self, item: &TopDecl) {
        if let TopDecl::Fn(fd) = item {
            let has_return = fd.return_type.is_some();
            let key = if let Some(recv_name) = &fd.receiver {
                format!("{}.{}", recv_name.name, fd.name.name)
            } else {
                fd.name.name.clone()
            };
            self.functions.insert(key, (fd.params.len(), has_return));
        }
        if let TopDecl::Module(md) = item {
            for sub in &md.items {
                self.register_functions(sub);
            }
        }
    }

    fn declare_functions_ir(&mut self, item: &TopDecl) -> Result<(), String> {
        if let TopDecl::Fn(fd) = item {
            let ret_llvm = fd.return_type.as_ref()
                .map(|t| Self::axiom_to_llvm_type(&Self::type_from_ast(t)))
                .unwrap_or("void");
            let name = if let Some(recv_name) = &fd.receiver {
                format!("{}.{}", recv_name.name, fd.name.name)
            } else {
                fd.name.name.clone()
            };
            let param_count = fd.params.len();
            let params_str = "i64, ".repeat(param_count);
            let params_str = params_str.trim_end_matches(", ");
            self.emitln(&format!("declare {ret_llvm} @{name}({params_str})"));
        }
        if let TopDecl::Module(md) = item {
            for sub in &md.items {
                self.declare_functions_ir(sub)?;
            }
        }
        Ok(())
    }

    fn compile_top_decl(&mut self, item: &TopDecl) -> Result<(), String> {
        match item {
            TopDecl::Fn(fd) => self.compile_fn(fd),
            TopDecl::Module(md) => {
                for sub in &md.items {
                    self.compile_top_decl(sub)?;
                }
                Ok(())
            }
            _ => Ok(()),
        }
    }

    fn compile_fn(&mut self, fd: &FnDecl) -> Result<(), String> {
        self.push_scope();
        self.block_counter = 0;
        self.tmp_counter = 0;

        let ret_llvm = fd.return_type.as_ref()
            .map(|t| Self::axiom_to_llvm_type(&Self::type_from_ast(t)))
            .unwrap_or("void");
        self.current_return_type = ret_llvm.to_string();

        let name = if let Some(recv_name) = &fd.receiver {
            format!("{}.{}", recv_name.name, fd.name.name)
        } else {
            fd.name.name.clone()
        };
        self.current_fn = Some(name.clone());

        let params_str: Vec<String> = fd.params.iter()
            .enumerate()
            .map(|(i, p)| {
                let llvm_ty = Self::axiom_to_llvm_type(&Self::type_from_ast(&p.ty));
                format!("{llvm_ty} %param{i}")
            })
            .collect();

        self.emitln(&format!("define {ret_llvm} @{name}({}) {{", params_str.join(", ")));

        // Entry block
        let entry_block = self.fresh_block("entry");
        self.emitln(&format!("{entry_block}:"));

        // Allocate parameters as locals
        for (i, param) in fd.params.iter().enumerate() {
            let llvm_ty = Self::axiom_to_llvm_type(&Self::type_from_ast(&param.ty));
            let alloca = self.fresh_tmp();
            self.emitln(&format!("  {alloca} = alloca {llvm_ty}"));
            self.emitln(&format!("  store {llvm_ty} %param{i}, {llvm_ty}* {alloca}"));
            self.add_local(&param.name.name, alloca);
        }

        // Compile body
        if let Some(ref body) = fd.body {
            self.compile_block(body, fd.return_type.is_some())?;
        }

        // Implicit return
        if fd.return_type.is_none() {
            self.emitln("  ret void");
        }

        self.emitln("}\n");
        self.pop_scope();
        self.current_fn = None;
        Ok(())
    }

    fn compile_block(&mut self, block: &Block, is_expression: bool) -> Result<Option<String>, String> {
        let mut last_result = None;

        for (idx, item) in block.stmts.iter().enumerate() {
            let is_last = idx == block.stmts.len() - 1;
            match item {
                StmtOrExpr::Stmt(stmt) => {
                    self.compile_stmt(stmt)?;
                }
                StmtOrExpr::Expr(expr) => {
                    let result = self.compile_expr(expr)?;
                    if is_last && is_expression {
                        // This is the tail expression — return it
                        let ret_ty = &self.current_return_type.clone();
                        self.emitln(&format!("  ret {ret_ty} {result}"));
                    }
                    last_result = Some(result);
                }
            }
        }
        Ok(last_result)
    }

    fn compile_stmt(&mut self, stmt: &Stmt) -> Result<(), String> {
        match stmt {
            Stmt::Let(name, _ty, value, _) => {
                let val = self.compile_expr(value)?;
                let llvm_ty = self.infer_llvm_type(value);
                let alloca = self.fresh_tmp();
                self.emitln(&format!("  {alloca} = alloca {llvm_ty}"));
                self.emitln(&format!("  store {llvm_ty} {val}, {llvm_ty}* {alloca}"));
                self.add_local(&name.name, alloca);
            }
            Stmt::Var(name, _ty, value, _) => {
                let val = self.compile_expr(value)?;
                let llvm_ty = self.infer_llvm_type(value);
                let alloca = self.fresh_tmp();
                self.emitln(&format!("  {alloca} = alloca {llvm_ty}"));
                self.emitln(&format!("  store {llvm_ty} {val}, {llvm_ty}* {alloca}"));
                self.add_local(&name.name, alloca);
            }
            Stmt::Assign(place, value, _) => {
                let val = self.compile_expr(value)?;
                if let Expr::Ident(ident) = place {
                    if let Some(ptr) = self.lookup_local(&ident.name).cloned() {
                        let llvm_ty = self.infer_llvm_type(value);
                        self.emitln(&format!("  store {llvm_ty} {val}, {llvm_ty}* {ptr}"));
                    }
                }
            }
            Stmt::Return(expr, _) => {
                if let Some(e) = expr {
                    let val = self.compile_expr(e)?;
                    let ret_ty = self.current_return_type.clone();
                    self.emitln(&format!("  ret {ret_ty} {val}"));
                } else {
                    self.emitln("  ret void");
                }
            }
            Stmt::Expr(expr, _) => {
                self.compile_expr(expr)?;
            }
            Stmt::If(cond, then_block, elifs, else_block, _) => {
                let cond_val = self.compile_expr(cond)?;
                let then_label = self.fresh_block("then");
                let merge_label = self.fresh_block("merge");

                let else_label = if !elifs.is_empty() || else_block.is_some() {
                    self.fresh_block("else")
                } else {
                    merge_label.clone()
                };

                self.emitln(&format!("  br i1 {cond_val}, label %{then_label}, label %{else_label}"));
                self.emitln(&format!("\n{then_label}:"));
                self.compile_block(then_block, false)?;
                self.emitln(&format!("  br label %{merge_label}"));

                // Elif chain
                let mut prev_label = if elifs.is_empty() && else_block.is_none() {
                    merge_label.clone()
                } else {
                    else_label.clone()
                };

                for (i, (econd, eblock)) in elifs.iter().enumerate() {
                    self.emitln(&format!("\n{prev_label}:"));
                    let econd_val = self.compile_expr(econd)?;
                    let elif_then = self.fresh_block("elif_then");
                    let elif_next = if i + 1 < elifs.len() || else_block.is_some() {
                        self.fresh_block("elif_next")
                    } else {
                        merge_label.clone()
                    };
                    self.emitln(&format!("  br i1 {econd_val}, label %{elif_then}, label %{elif_next}"));
                    self.emitln(&format!("\n{elif_then}:"));
                    self.compile_block(eblock, false)?;
                    self.emitln(&format!("  br label %{merge_label}"));
                    prev_label = elif_next;
                }

                // Else block
                if let Some(eb) = else_block {
                    self.emitln(&format!("\n{prev_label}:"));
                    self.compile_block(eb, false)?;
                    self.emitln(&format!("  br label %{merge_label}"));
                } else if elifs.is_empty() {
                    // No else case for simple if — the else block is just a merge jump
                    self.emitln(&format!("\n{prev_label}:"));
                    self.emitln(&format!("  br label %{merge_label}"));
                } else {
                    self.emitln(&format!("\n{prev_label}:"));
                    self.emitln(&format!("  br label %{merge_label}"));
                }

                self.emitln(&format!("\n{merge_label}:"));
            }
            Stmt::Match(_expr, arms, _) => {
                // Phase 0 simplified match: use first arm as default
                let merge_label = self.fresh_block("match_merge");
                let default_label = self.fresh_block("match_default");
                self.emitln(&format!("  br label %{default_label}"));
                self.emitln(&format!("\n{default_label}:"));
                if let Some(first_arm) = arms.first() {
                    match &first_arm.body {
                        MatchBody::Block(b) => { self.compile_block(b, false)?; }
                        MatchBody::Expr(e) => { self.compile_expr(e)?; }
                    }
                }
                self.emitln(&format!("  br label %{merge_label}"));
                self.emitln(&format!("\n{merge_label}:"));
            }
            Stmt::While(cond, body, _) => {
                let loop_cond = self.fresh_block("while_cond");
                let loop_body = self.fresh_block("while_body");
                let loop_exit = self.fresh_block("while_exit");

                self.emitln(&format!("  br label %{loop_cond}"));
                self.emitln(&format!("\n{loop_cond}:"));
                let cond_val = self.compile_expr(cond)?;
                self.emitln(&format!("  br i1 {cond_val}, label %{loop_body}, label %{loop_exit}"));
                self.emitln(&format!("\n{loop_body}:"));
                self.compile_block(body, false)?;
                self.emitln(&format!("  br label %{loop_cond}"));
                self.emitln(&format!("\n{loop_exit}:"));
            }
            Stmt::For(_, _, body, _) => {
                // Phase 0: simplified for — just execute body once
                self.compile_block(body, false)?;
            }
            Stmt::Spawn(body, _) => {
                self.compile_block(body, false)?;
            }
        }
        Ok(())
    }

    fn compile_expr(&mut self, expr: &Expr) -> Result<String, String> {
        match expr {
            Expr::Ident(ident) => {
                if let Some(ptr) = self.lookup_local(&ident.name).cloned() {
                    let tmp = self.fresh_tmp();
                    self.emitln(&format!("  {tmp} = load i64, i64* {ptr}"));
                    Ok(tmp)
                } else {
                    Ok("0".to_string())
                }
            }
            Expr::Int(n, _) => {
                Ok(format!("{n}"))
            }
            Expr::Float(f, _) => {
                Ok(format!("{f:.6}"))
            }
            Expr::Bool(b, _) => {
                Ok(if *b { "1".to_string() } else { "0".to_string() })
            }
            Expr::Str(s, _) => {
                let str_id = self.str_counter;
                self.str_counter += 1;
                let label = format!("@.str{str_id}");
                let escaped = s.replace('\\', "\\\\").replace('"', "\\\"")
                    .replace('\n', "\\0A").replace('\t', "\\09");
                self.strings.push(format!(
                    "{label} = private unnamed_addr constant [{}, x i8] c\"{}\\00\"",
                    s.len() + 1, escaped
                ));
                let tmp = self.fresh_tmp();
                self.emitln(&format!("  {tmp} = getelementptr [{}, x i8], [{}, x i8]* {label}, i64 0, i64 0", s.len() + 1, s.len() + 1));
                Ok(tmp)
            }
            Expr::Char(c, _) => {
                Ok(format!("{}", *c as u32))
            }
            Expr::Paren(inner, _) => self.compile_expr(inner),
            Expr::Unary(op, inner, _) => {
                let val = self.compile_expr(inner)?;
                let tmp = self.fresh_tmp();
                match op {
                    UnaryOp::Neg => {
                        if let Expr::Float(..) = **inner {
                            self.emitln(&format!("  {tmp} = fneg double {val}"));
                        } else {
                            self.emitln(&format!("  {tmp} = sub i64 0, {val}"));
                        }
                    }
                    UnaryOp::Not => {
                        self.emitln(&format!("  {tmp} = xor i64 {val}, 1"));
                    }
                    UnaryOp::Ref | UnaryOp::MutRef => return Ok(val),
                }
                Ok(tmp)
            }
            Expr::Binary(left, op, right, _) => {
                let l = self.compile_expr(left)?;
                let r = self.compile_expr(right)?;
                let tmp = self.fresh_tmp();
                let is_float = matches!(**left, Expr::Float(..)) || matches!(**right, Expr::Float(..));
                let (ty, inst) = match op {
                    BinOp::Add => (if is_float { "double" } else { "i64" }, if is_float { "fadd" } else { "add" }),
                    BinOp::Sub => (if is_float { "double" } else { "i64" }, if is_float { "fsub" } else { "sub" }),
                    BinOp::Mul => (if is_float { "double" } else { "i64" }, if is_float { "fmul" } else { "mul" }),
                    BinOp::Div => (if is_float { "double" } else { "i64" }, if is_float { "fdiv" } else { "sdiv" }),
                    BinOp::Rem => (if is_float { "double" } else { "i64" }, if is_float { "frem" } else { "srem" }),
                    BinOp::Eq => ("i64", "icmp eq"),
                    BinOp::Neq => ("i64", "icmp ne"),
                    BinOp::Lt => ("i64", "icmp slt"),
                    BinOp::Gt => ("i64", "icmp sgt"),
                    BinOp::Le => ("i64", "icmp sle"),
                    BinOp::Ge => ("i64", "icmp sge"),
                    BinOp::And => ("i64", "and"),
                    BinOp::Or => ("i64", "or"),
                    BinOp::Assign => return Ok(r),
                };
                if inst.starts_with("icmp") {
                    self.emitln(&format!("  {tmp} = {inst} {ty} {l}, {r}"));
                } else {
                    self.emitln(&format!("  {tmp} = {inst} {ty} {l}, {r}"));
                }
                Ok(tmp)
            }
            Expr::Try(inner, _) => self.compile_expr(inner),
            Expr::Imply(left, right, _) => {
                let l = self.compile_expr(left)?;
                let r = self.compile_expr(right)?;
                let tmp1 = self.fresh_tmp();
                let tmp2 = self.fresh_tmp();
                self.emitln(&format!("  {tmp1} = xor i64 {l}, 1"));
                self.emitln(&format!("  {tmp2} = or i64 {tmp1}, {r}"));
                Ok(tmp2)
            }
            Expr::Is(_, _, _) => Ok("1".to_string()),
            Expr::Field(_, _, _) => Ok("0".to_string()), // simplified
            Expr::Call(func, args, _) => {
                if let Expr::Ident(ref name) = **func {
                    let compiled_args: Vec<String> = args.iter()
                        .map(|a| self.compile_expr(a))
                        .collect::<Result<Vec<_>, _>>()?;
                    if name.name == "io" {
                        // Print call — use puts for now
                        if let Some(arg) = compiled_args.first() {
                            let tmp = self.fresh_tmp();
                            self.emitln(&format!("  {tmp} = call i32 @puts(i8* {arg})"));
                            return Ok(tmp);
                        }
                        return Ok("0".to_string());
                    }
                    let tmp = self.fresh_tmp();
                    let ret_ty = if let Some((_, has_ret)) = self.functions.get(&name.name) {
                        if *has_ret { "i64" } else { "void" }
                    } else {
                        "i64"
                    };
                    let args_str = compiled_args.iter()
                        .map(|a| format!("i64 {a}"))
                        .collect::<Vec<_>>()
                        .join(", ");
                    if ret_ty == "void" {
                        self.emitln(&format!("  call void @{}({})", name.name, args_str));
                        Ok(tmp) // dummy
                    } else {
                        self.emitln(&format!("  {tmp} = call {ret_ty} @{}({})", name.name, args_str));
                        Ok(tmp)
                    }
                } else {
                    Ok("0".to_string())
                }
            }
            Expr::Index(_, _, _) => Ok("0".to_string()),
            Expr::AtPre(inner, _) => self.compile_expr(inner),
            Expr::Ref(inner, _) | Expr::MutRef(inner, _) => self.compile_expr(inner),
            Expr::Some(inner, _) => self.compile_expr(inner),
            Expr::None(_) => Ok("0".to_string()),
            Expr::Ok(inner, _) => self.compile_expr(inner),
            Expr::Err(inner, _) => self.compile_expr(inner),
            Expr::Struct(name, fields, _) => {
                let struct_ty = format!("%struct.{}", name.name);
                let alloca = self.fresh_tmp();
                self.emitln(&format!("  {alloca} = alloca {struct_ty}"));
                for (i, (_, val)) in fields.iter().enumerate() {
                    let field_val = self.compile_expr(val)?;
                    let gep = self.fresh_tmp();
                    self.emitln(&format!("  {gep} = getelementptr {struct_ty}, {struct_ty}* {alloca}, i32 0, i32 {i}"));
                    self.emitln(&format!("  store i64 {field_val}, i64* {gep}"));
                }
                let loaded = self.fresh_tmp();
                self.emitln(&format!("  {loaded} = load {struct_ty}, {struct_ty}* {alloca}"));
                Ok(loaded)
            }
            Expr::Array(_, _) => Ok("0".to_string()),
            Expr::Closure(_, _, _) | Expr::PipeClosure(_, _, _) => Ok("0".to_string()),
            Expr::Await(inner, _) => self.compile_expr(inner),
            Expr::Comptime(inner, _) => self.compile_expr(inner),
        }
    }

    fn infer_llvm_type(&self, expr: &Expr) -> &'static str {
        match expr {
            Expr::Int(_, _) | Expr::Bool(_, _) => "i64",
            Expr::Float(_, _) => "double",
            Expr::Str(_, _) | Expr::Char(_, _) => "i8*",
            Expr::Struct(_name, _, _) => {
                // We'll use i64 for all struct values in Phase 0
                "i64"
            }
            _ => "i64",
        }
    }
}
