use std::env;
use std::fs;
use std::process;

#[derive(Debug)]
struct Function {
    name: String,
    params: Vec<(String, String)>,
    return_type: String,
    variadic: bool,
    nullable_return: bool,
}

#[derive(Debug)]
struct Library {
    name: String,
    functions: Vec<Function>,
}

fn main() {
    let args: Vec<String> = env::args().collect();
    let mut json_mode = false;
    let mut input_file = None;

    let mut i = 1;
    while i < args.len() {
        match args[i].as_str() {
            "--json" => json_mode = true,
            f => input_file = Some(f.to_string()),
        }
        i += 1;
    }

    let input_file = input_file.unwrap_or_else(|| {
        eprintln!("axiom ffigen: missing binding specification file");
        eprintln!("Usage: axiom ffigen [--json] <spec.axiom-bind>");
        process::exit(1);
    });

    let source = fs::read_to_string(&input_file).unwrap_or_else(|e| {
        eprintln!("axiom ffigen: cannot read {}: {}", input_file, e);
        process::exit(1);
    });

    let libraries = parse_spec(&source);

    if json_mode {
        output_json(&libraries);
    } else {
        output_axiom(&libraries);
    }
}

fn parse_spec(source: &str) -> Vec<Library> {
    let mut libraries = Vec::new();
    let mut current_lib: Option<Library> = None;

    for line in source.lines() {
        let line = line.trim();
        if line.is_empty() || line.starts_with('#') {
            continue;
        }

        if line.ends_with('{') {
            let name = line
                .trim_end_matches('{')
                .trim()
                .strip_prefix("library")
                .unwrap_or("")
                .trim()
                .trim_matches('"');
            if !name.is_empty() {
                current_lib = Some(Library { name: name.to_string(), functions: Vec::new() });
            }
        } else if line == "}" {
            if let Some(lib) = current_lib.take() {
                libraries.push(lib);
            }
        } else if line.starts_with("fn ") {
            if let Some(ref mut lib) = current_lib {
                if let Some(func) = parse_fn_spec(line) {
                    lib.functions.push(func);
                }
            }
        }
    }

    libraries
}

fn parse_fn_spec(line: &str) -> Option<Function> {
    let line = line.trim().strip_prefix("fn ")?;
    let line = line.trim_end_matches(';');

    let open_paren = line.find('(')?;
    let name = line[..open_paren].trim().to_string();
    let rest = &line[open_paren..];

    let close_paren = rest.find(')')?;
    let params_str = &rest[1..close_paren];

    let mut params = Vec::new();
    let mut variadic = false;

    if params_str.contains("...") {
        variadic = true;
    }

    for param in params_str
        .split(',')
        .map(|s| s.trim())
        .filter(|s| !s.is_empty() && *s != "...")
    {
        let parts: Vec<&str> = param.split(':').collect();
        if parts.len() == 2 {
            params.push((parts[0].trim().to_string(), parts[1].trim().to_string()));
        }
    }

    let after_paren = &rest[close_paren + 1..];
    let return_type = if let Some(arrow_pos) = after_paren.find("->") {
        after_paren[arrow_pos + 2..].trim().to_string()
    } else {
        "void".to_string()
    };

    let nullable_return = after_paren.contains("nullable");

    Some(Function { name, params, return_type, variadic, nullable_return })
}

fn output_axiom(libraries: &[Library]) {
    println!("// Auto-generated by axiom ffigen v0.7.0");
    println!();

    for lib in libraries {
        println!("extern \"C\" {{");
        println!("  // {}", lib.name);
        for func in &lib.functions {
            print!("  fn {}(", func.name);
            for (i, (pname, ptype)) in func.params.iter().enumerate() {
                if i > 0 {
                    print!(", ");
                }
                print!("{}: {}", pname, axiom_type(ptype));
            }
            if func.variadic {
                if !func.params.is_empty() {
                    print!(", ");
                }
                print!("...");
            }
            print!(")");
            if func.return_type != "void" {
                print!(" -> {}", axiom_type(&func.return_type));
            }
            println!();

            let contracts = infer_contracts(func);
            if !contracts.is_empty() {
                for c in &contracts {
                    println!("    {}", c);
                }
            }
        }
        println!("}}");
        println!();
    }
}

fn axiom_type(c_type: &str) -> &str {
    match c_type {
        "i8" => "Int8",
        "u8" => "UInt8",
        "i16" => "Int16",
        "u16" => "UInt16",
        "i32" => "Int32",
        "u32" => "UInt32",
        "i64" => "Int64",
        "u64" => "UInt",
        "f32" => "Float32",
        "f64" => "Float64",
        "str" => "Str",
        "ptr" => "*UInt8",
        "void" => "",
        "bool" => "Bool",
        other => other,
    }
}

fn infer_contracts(func: &Function) -> Vec<String> {
    let mut contracts = Vec::new();

    if func.name == "malloc" {
        contracts.push("requires: size > 0".to_string());
        contracts.push("ensures: result != null".to_string());
        return contracts;
    }

    if func.name == "free" {
        return contracts;
    }

    for (pname, ptype) in &func.params {
        match ptype.as_str() {
            "str" => contracts.push(format!("requires: {} != null", pname)),
            "ptr" => {
                if func.name != "free" {
                    contracts.push(format!("requires: {} != null", pname));
                }
            }
            _ => {}
        }
    }

    if func.return_type == "ptr" && !func.nullable_return {
        contracts.push("ensures: result != null".to_string());
    }

    contracts
}

fn output_json(libraries: &[Library]) {
    let mut json_libs = Vec::new();
    for lib in libraries {
        let mut json_funcs = Vec::new();
        for func in &lib.functions {
            let mut json_params = Vec::new();
            for (name, ctype) in &func.params {
                json_params.push(serde_json::json!({
                    "name": name,
                    "c_type": ctype,
                    "axiom_type": axiom_type(ctype)
                }));
            }
            json_funcs.push(serde_json::json!({
                "name": func.name,
                "params": json_params,
                "return_type": axiom_type(&func.return_type),
                "variadic": func.variadic,
                "contracts": infer_contracts(func)
            }));
        }
        json_libs.push(serde_json::json!({
            "name": lib.name,
            "functions": json_funcs
        }));
    }
    println!("{}", serde_json::to_string_pretty(&json_libs).unwrap());
}
