// XIOM — Contract Verifier
// Copyright (c) 2026 Eleftherios Notas
// Licensed under the MIT or Apache-2.0 license, at your option.

use xiom_ast::*;

pub struct SMTGenerator {
    buf: String,
}

impl SMTGenerator {
    pub fn new() -> Self {
        Self { buf: String::new() }
    }

    pub fn generate(&mut self, program: &Program) -> String {
        self.emit("; XIOM Contract Verification — SMT-LIB 2.6");
        self.emit("; Generated by xiom verify v0.8.0");
        self.emit("");
        self.emit("(set-logic QF_NRA)");
        self.emit("");

        for item in &program.items {
            self.process_top_decl(item);
        }

        self.emit("(check-sat)");
        std::mem::take(&mut self.buf)
    }

    fn process_top_decl(&mut self, item: &TopDecl) {
        match item {
            TopDecl::Fn(f) if !f.contracts.is_empty() => {
                self.verify_function(f);
            }
            TopDecl::Type(td) if !td.invariants.is_empty() => {
                self.verify_type_invariants(td);
            }
            TopDecl::Module(m) => {
                for item in &m.items {
                    self.process_top_decl(item);
                }
            }
            _ => {}
        }
    }

    fn verify_function(&mut self, f: &FnDecl) {
        self.emit(&format!("; === Function: {} ===", f.name.name));

        for param in &f.params {
            let smt_ty = xiom_to_smt_type(&param.ty);
            self.emit(&format!("(declare-const {} {})", param.name.name, smt_ty));
        }

        if f.return_type.is_some() {
            let smt_ty = xiom_to_smt_type(f.return_type.as_ref().unwrap());
            self.emit(&format!("(declare-const result {})", smt_ty));
        }

        self.emit("");

        for contract in &f.contracts {
            if matches!(contract, ContractClause::Requires(..)) {
                self.emit(&format!("; requires: {}", expr_display(&clause_expr(contract))));
                self.emit("(assert ");
                self.translate_expr(&clause_expr(contract), 0);
                self.emit(")");
                self.emit("");
            }
        }

        for contract in &f.contracts {
            if !matches!(contract, ContractClause::Requires(..)) {
                self.emit(&format!("; ensures: {}", expr_display(&clause_expr(contract))));
                self.emit("(push)");
                self.emit("(assert (not ");
                self.translate_expr(&clause_expr(contract), 0);
                self.emit("))");
                self.emit("(check-sat)");
                self.emit("(pop)");
                self.emit("");
            }
        }
    }

    fn verify_type_invariants(&mut self, td: &TypeDecl) {
        self.emit(&format!("; === Type: {} — Invariants ===", td.name.name));
        for (i, inv) in td.invariants.iter().enumerate() {
            self.emit(&format!("; invariant {}: {}", i, expr_display(inv)));
        }
        self.emit("");
    }

    fn translate_expr(&mut self, expr: &Expr, indent: usize) {
        let _ = indent;
        match expr {
            Expr::Int(n, _) => self.buf.push_str(&n.to_string()),
            Expr::Float(f, _) => self.buf.push_str(&f.to_string()),
            Expr::Bool(b, _) => self.buf.push_str(if *b { "true" } else { "false" }),
            Expr::Ident(id) => self.buf.push_str(&id.name),
            Expr::Binary(left, op, right, _) => {
                if op == &BinOp::Neq {
                    self.buf.push_str("(not (= ");
                    self.translate_expr(left, 0);
                    self.buf.push(' ');
                    self.translate_expr(right, 0);
                    self.buf.push_str("))");
                } else {
                    let smt_op = match op {
                        BinOp::Add => "+",
                        BinOp::Sub => "-",
                        BinOp::Mul => "*",
                        BinOp::Div => "/",
                        BinOp::Eq => "=",
                        BinOp::Lt => "<",
                        BinOp::Gt => ">",
                        BinOp::Le => "<=",
                        BinOp::Ge => ">=",
                        BinOp::And => "and",
                        BinOp::Or => "or",
                        _ => "=",
                    };
                    self.buf.push('(');
                    self.buf.push_str(smt_op);
                    self.buf.push(' ');
                    self.translate_expr(left, 0);
                    self.buf.push(' ');
                    self.translate_expr(right, 0);
                    self.buf.push(')');
                }
            }
            Expr::Unary(op, inner, _) => {
                match op {
                    UnaryOp::Not => {
                        self.buf.push_str("(not ");
                        self.translate_expr(inner, 0);
                        self.buf.push(')');
                    }
                    UnaryOp::Neg => {
                        self.buf.push_str("(- ");
                        self.translate_expr(inner, 0);
                        self.buf.push(')');
                    }
                    _ => self.translate_expr(inner, 0),
                }
            }
            Expr::Call(func, args, _) => {
                self.buf.push('(');
                self.translate_expr(func, 0);
                for arg in args {
                    self.buf.push(' ');
                    self.translate_expr(arg, 0);
                }
                self.buf.push(')');
            }
            _ => self.buf.push_str("true"),
        }
    }

    fn emit(&mut self, line: &str) {
        self.buf.push_str(line);
        self.buf.push('\n');
    }
}

fn xiom_to_smt_type(ty: &Type) -> &str {
    match ty {
        Type::Named(name, _) => match name.name.as_str() {
            "Int" | "Int64" | "Int32" | "UInt" => "Int",
            "Float64" | "Float32" => "Real",
            "Bool" => "Bool",
            _ => "Int",
        },
        _ => "Int",
    }
}

fn clause_expr(clause: &ContractClause) -> &Expr {
    match clause {
        ContractClause::Requires(e, _) | ContractClause::Ensures(e, _) => e,
    }
}

fn expr_display(expr: &Expr) -> String {
    match expr {
        Expr::Ident(id) => id.name.clone(),
        Expr::Int(n, _) => n.to_string(),
        Expr::Float(f, _) => f.to_string(),
        Expr::Bool(b, _) => {
            if *b { "true".to_string() } else { "false".to_string() }
        }
        Expr::Binary(left, op, right, _) => {
            let op_str = match op {
                BinOp::Add => "+",
                BinOp::Sub => "-",
                BinOp::Mul => "*",
                BinOp::Div => "/",
                BinOp::Eq => "==",
                BinOp::Neq => "!=",
                BinOp::Lt => "<",
                BinOp::Gt => ">",
                BinOp::Le => "<=",
                BinOp::Ge => ">=",
                BinOp::And => "&&",
                BinOp::Or => "||",
                _ => "?",
            };
            format!("{} {} {}", expr_display(left), op_str, expr_display(right))
        }
        Expr::Unary(op, inner, _) => match op {
            UnaryOp::Not => format!("!{}", expr_display(inner)),
            UnaryOp::Neg => format!("-{}", expr_display(inner)),
            _ => "?".to_string(),
        },
        _ => "?".to_string(),
    }
}
