# Copyright (c) 2026 Eleftherios Notas and XIOM Foundation
# SPDX-License-Identifier: MIT OR Apache-2.0

[package]
license.workspace = true
publish = false
name = "xiom-check"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
xiom-ast = { path = "../xiom-ast" }
xiom-lowering = { path = "../xiom-lowering" }
xiom-lexer = { path = "../xiom-lexer" }
xiom-parser = { path = "../xiom-parser" }

[dev-dependencies]
insta = { version = "1", features = ["yaml"] }
